services:
  - type: web
    name: fantasy-edge-api
    env: python
    region: oregon
    rootDir: apps/api
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: YAHOO_CLIENT_ID
        sync: false
      - key: YAHOO_CLIENT_SECRET
        sync: false
      - key: YAHOO_REDIRECT_URI
        value: https://api.misfits.westfam.media/auth/yahoo/callback
      - key: JWT_SECRET
        sync: false
      - key: TOKEN_CRYPTO_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://misfits.westfam.media
