services:
  - type: web
    name: fantasy-edge-api
    env: python
    plan: free
    rootDir: apps/api
    buildCommand: pip install -r requirements.txt
    # Free tier: no preDeployCommand; run migrations at start
    startCommand: bash -lc 'export PYTHONPATH="$PYTHONPATH:$(pwd)" && alembic upgrade head && exec uvicorn app.main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: YAHOO_CLIENT_ID
        sync: false
      - key: YAHOO_CLIENT_SECRET
        sync: false
      - key: YAHOO_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TOKEN_CRYPTO_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://misfits.westfam.media