# Fly.io config for the API service.
# Fill in the "app" name before deploying.
app = "REPLACE_ME_api"
primary_region = "iad"

[build]
  dockerfile = "../apps/api/Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
