# Fly.io config for the Celery worker service.
# Fill in the "app" name before deploying.
app = "REPLACE_ME_worker"
primary_region = "iad"

[build]
  dockerfile = "../services/worker/Dockerfile"

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
